let allQuestions=Array.isArray(window.QUESTION_BANK)?window.QUESTION_BANK.slice():[];let questions=allQuestions.slice();let current=0;let score=0;let userAnswers=[];let wrongQuestions=[];let answered=false;
const $=id=>document.getElementById(id);
const intro=$('intro'),quizScreen=$('quizScreen'),resultScreen=$('resultScreen'),startBtn=$('startBtn'),loading=$('loading'),loadError=$('loadError');
function init(){if(!allQuestions.length){loading.hidden=true;loadError.hidden=false;loadError.textContent='No se encontró el banco de preguntas. Asegúrate de que questions.js esté en la misma carpeta que quiz.html.';startBtn.disabled=true;return}loading.textContent=`${allQuestions.length} preguntas listas.`;startBtn.disabled=false;renderQuestion();}
function startQuiz(){questions=allQuestions.slice();current=0;score=0;userAnswers=Array(questions.length).fill(null);wrongQuestions=[];answered=false;intro.hidden=true;resultScreen.hidden=true;quizScreen.hidden=false;renderQuestion();window.scrollTo({top:0,behavior:'smooth'});}
function renderQuestion(){if(!questions.length)return;const q=questions[current];answered=userAnswers[current]!==null&&userAnswers[current]!==undefined;$('questionNumber').textContent=`Pregunta ${current+1} de ${questions.length}`;$('score').textContent=score;$('progressBar').style.width=`${((current+1)/questions.length)*100}%`;$('questionArea').innerHTML=`<div class="question-card"><h2>${escapeHtml(q.q)}</h2><div class="answer-list">${q.o.map((option,i)=>`<button class="answer-btn" data-index="${i}" type="button">${String.fromCharCode(65+i)}) ${escapeHtml(option)}</button>`).join('')}</div>${answered?`<div id="feedback" class="feedback"></div>`:''}</div>`;document.querySelectorAll('.answer-btn').forEach(btn=>btn.addEventListener('click',()=>answerQuestion(Number(btn.dataset.index))));$('previousBtn').disabled=current===0;$('continueBtn').disabled=!answered;if(answered)restoreAnswer();}
function answerQuestion(selected){if(answered)return;const q=questions[current];answered=true;userAnswers[current]=selected;if(selected===q.a)score++;else wrongQuestions.push(current);document.querySelectorAll('.answer-btn').forEach((btn,i)=>{btn.disabled=true;if(i===q.a)btn.classList.add('correct');if(i===selected&&selected!==q.a)btn.classList.add('wrong')});$('score').textContent=score;showFeedback(q,selected);$('continueBtn').disabled=false;}
function showFeedback(q,selected){const feedback=$('feedback')||document.createElement('div');if(!feedback.id){feedback.id='feedback';feedback.className='feedback';$('questionArea').querySelector('.question-card').appendChild(feedback)}const ok=selected===q.a;feedback.innerHTML=`<strong>${ok?'✅ ¡Correcta!':'❌ Incorrecta'}</strong><div>Respuesta: <b>${String.fromCharCode(65+q.a)}) ${escapeHtml(q.o[q.a])}</b></div>${q.e?`<div style="margin-top:6px">${escapeHtml(q.e)}</div>`:''}`;}
function restoreAnswer(){const q=questions[current],selected=userAnswers[current];document.querySelectorAll('.answer-btn').forEach((btn,i)=>{btn.disabled=true;if(i===q.a)btn.classList.add('correct');if(i===selected&&selected!==q.a)btn.classList.add('wrong')});showFeedback(q,selected);}
function nextQuestion(){if(!answered)return;if(current<questions.length-1){current++;renderQuestion();window.scrollTo({top:quizScreen.offsetTop-65,behavior:'smooth'})}else finishQuiz();}
function previousQuestion(){if(current>0){current--;renderQuestion();window.scrollTo({top:quizScreen.offsetTop-65,behavior:'smooth'})}}
function finishQuiz(){quizScreen.hidden=true;resultScreen.hidden=false;const total=questions.length;const wrong=total-score;const pct=Math.round(score/total*100);$('percentage').textContent=`${pct}%`;$('correctCount').textContent=score;$('wrongCount').textContent=wrong;$('resultSummary').textContent=`Obtuviste ${score} de ${total} correctas.`;window.scrollTo({top:0,behavior:'smooth'})}
function restartQuiz(){if(confirm('¿Quieres reiniciar el quiz desde la primera pregunta?'))startQuiz()}
function retryQuiz(){startQuiz()}
function reviewWrongAnswers(){if(!wrongQuestions.length){alert('¡No tienes errores para revisar! 🎉');return}const wrongSet=new Set(wrongQuestions);questions=allQuestions.filter((_,i)=>wrongSet.has(i));current=0;score=0;userAnswers=Array(questions.length).fill(null);wrongQuestions=[];answered=false;resultScreen.hidden=true;quizScreen.hidden=false;renderQuestion();window.scrollTo({top:0,behavior:'smooth'})}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
startBtn.addEventListener('click',startQuiz);$('continueBtn').addEventListener('click',nextQuestion);$('previousBtn').addEventListener('click',previousQuestion);$('retryBtn').addEventListener('click',retryQuiz);$('reviewBtn').addEventListener('click',reviewWrongAnswers);$('restartTop').addEventListener('click',()=>{if(!quizScreen.hidden)restartQuiz();else startQuiz()});init();
